const LOGIN_IDS = 'LOGIN_IDS'
const USER_IDS = 'USER_IDS'
const ACTIVITY_IDS = 'ACTIVITY_IDS'
const ENUMERATION_IDS = 'ENUMERATION_IDS'

const LOGIN_IDS_LOGIN = 'LOGIN_IDS_LOGIN'
const LOGIN_IDS_LOGOUT = 'LOGIN_IDS_LOGOUT'
const USER_IDS_GET_USER_DATA = 'USER_IDS_GET_USER_DATA'
const ACTIVITY_IDS_GET_USER_ACTIVITIES = 'ACTIVITY_IDS_GET_USER_ACTIVITIES'
const ACTIVITY_IDS_GET_USER_ACTIVITIES_PORTIONS = 'ACTIVITY_IDS_GET_USER_ACTIVITIES_PORTIONS'
const ACTIVITY_IDS_CREATE_NEW_ACTIVITY = 'ACTIVITY_IDS_CREATE_NEW_ACTIVITY'
const ENUMERATION_IDS_GET_PORTION_HEALTHINESSES = 'ENUMERATION_IDS_GET_PORTION_HEALTHINESSES'
const ENUMERATION_IDS_GET_PORTION_SIZES = 'ENUMERATION_IDS_GET_PORTION_SIZES'

const LOGIN_IDS_REQUESTS = {
  LOGIN_IDS_LOGIN,
  LOGIN_IDS_LOGOUT,
}

const USER_IDS_REQUESTS = {
  USER_IDS_GET_USER_DATA,
}

const ACTIVITY_IDS_REQUESTS = {
  ACTIVITY_IDS_GET_USER_ACTIVITIES,
  ACTIVITY_IDS_GET_USER_ACTIVITIES_PORTIONS,
  ACTIVITY_IDS_CREATE_NEW_ACTIVITY,
}

const ENUMERATION_IDS_REQUESTS = {
  ENUMERATION_IDS_GET_PORTION_HEALTHINESSES,
  ENUMERATION_IDS_GET_PORTION_SIZES,
}

const API_IDS = {
  [LOGIN_IDS]: LOGIN_IDS_REQUESTS,
  [USER_IDS]: USER_IDS_REQUESTS,
  [ACTIVITY_IDS]: ACTIVITY_IDS_REQUESTS,
  [ENUMERATION_IDS]: ENUMERATION_IDS_REQUESTS,
}

export {
  API_IDS,
  LOGIN_IDS_REQUESTS,
  USER_IDS_REQUESTS,
  ACTIVITY_IDS_REQUESTS,
  ENUMERATION_IDS_REQUESTS,
}
